version: 2
jobs:
  build:
    docker:
      - image: circleci/node
        environment:
          TERM: xterm
    steps:
      # checkout code
      - checkout

      # install dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      # linter
      - run:
          name: Linter
          command: npm run lint
